### ISSUE TITLE
Essentia tube networks spiraling out of control.

### ISSUE THREAD

**Issue by KillerRamer** [Lycaonj/AdvancedThaumaturgy#10]
So after a few days I noticed that some aspects were outright disappearing, not going to empty jars.  Later today however seeing empty jars sucking essentia from a labeled  network and another friend having trouble with their tubes. We removed the ethereal jars, It didn't fix that issue bu it did reveal something interesting.

Essentia that had gone missing started filling the empty jars. Four lucrum I had thought  I had made two days prior, had suddenly appeared and started filling the first jar, however When it came to Arbor The void jar that was labeled began fighting with another jar over one point of arbor. 

Breaking the tubes to fix this did not fix the issue, I wasn't sure where to look but seeing as Eth jars caused the clog in the first place it would be best to send it here.

**Comment by Lycaonj** [comment]
Fixed in build 20.
