### ISSUE TITLE
Reproducing bug that turns phials into labels.

### ISSUE THREAD

**Issue by KillerRamer** [Lycaonj/AdvancedThaumaturgy#12]
Step one: Take a phial of either Aurum or saxum (might possibly work with others but these are two I managed to make it happen with.) And right click on Ethereal Jar.

Step two: Be amazed as the sound of labeling a jar spams your ears as if someone were impatiently flipping through a book, and your essentia stockpile continues to shrink as you attempt to fill the Ethereal jar with essentia via phial.

**Comment by Lycaonj** [comment]
Fixed in build 21 hopefully.
