### ISSUE TITLE
Casting to EntityPlayer in ATServerCommand

### ISSUE THREAD

**Issue by izstas** [Lycaonj/AdvancedThaumaturgy#16]
Please check if the command sender is instance of EntityPlayer before casting it in [ATServerCommand.java](https://github.com/Lycaonj/AdvancedThaumaturgy/blob/master/main/java/net/ixios/advancedthaumaturgy/misc/ATServerCommand.java#L42). This causes issues when entering commands from server console, including /help command, which tries to check if the sender can use your command.

**Comment by Lycaonj** [comment]
Fixed in build 24.  Thanks for the heads up.
