### ISSUE TITLE
(SUGGESTION) Thaumonomicon prefixes

### ISSUE THREAD

**Issue by LemmaEOF** [Lycaonj/AdvancedThaumaturgy#17]
I'd really like it if you added a prefix to thaumonomicon splashes for items, so you can tell that the items are from AT. For example, Thaumic Tinkerer puts [TT] as a prefix in all the blue text splash descriptions for his researches. It helps clear up confusion. COuld you do that, please? Thanks!

**Comment by Lycaonj** [comment]
I had them in at one point, but lost the code.  I'll readd that to the research icons that are not directly on the AT thaumonomicon tab. :)
