### ISSUE TITLE
minecraft crashes when I open the Advanced Thaumaturgy tab in Creative.

### ISSUE THREAD

**Issue by Problemperson** [Lycaonj/AdvancedThaumaturgy#18]
---- Minecraft Crash Report ----
// You're mean.

Time: 2/22/14 9:20 PM
Description: Rendering screen

java.lang.NoSuchMethodError: thaumcraft.common.items.wands.WandManager.getTotalVisDiscount(Lnet/minecraft/entity/player/EntityPlayer;)F
    at net.ixios.advancedthaumaturgy.items.ItemMercurialWand.func_77624_a(ItemMercurialWand.java:233)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:663)
    at net.minecraft.client.gui.inventory.GuiContainer.func_74184_a(GuiContainer.java:226)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_74184_a(GuiContainerCreative.java:778)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:202)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(SourceFile:31)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:683)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1036)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.ixios.advancedthaumaturgy.items.ItemMercurialWand.func_77624_a(ItemMercurialWand.java:233)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:663)
    at net.minecraft.client.gui.inventory.GuiContainer.func_74184_a(GuiContainer.java:226)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_74184_a(GuiContainerCreative.java:778)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:202)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(SourceFile:31)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:683)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (145, 99). Absolute: (291, 281)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['JakeJake15'/31, l='MpServer', x=-324.64, y=5.62, z=-167.49]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-429,4,-49), Chunk: (at 3,0,15 in -27,-4; contains blocks -432,0,-64 to -417,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 6687 game time, 6687 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 57 total; [EntityVillager['Villager'/0, l='MpServer', x=-307.94, y=5.00, z=-208.63], EntityVillager['Villager'/1, l='MpServer', x=-303.59, y=5.00, z=-207.22], EntityVillager['Villager'/2, l='MpServer', x=-297.88, y=5.00, z=-193.69], EntityItem['item.item.seeds'/78795, l='MpServer', x=-285.97, y=5.13, z=-151.34], EntityVillager['Villager'/3, l='MpServer', x=-300.63, y=4.00, z=-209.59], EntityItem['item.item.wheat'/78794, l='MpServer', x=-286.66, y=5.13, z=-149.72], EntityVillager['Villager'/4, l='MpServer', x=-307.09, y=4.00, z=-199.72], EntityVillager['Villager'/5, l='MpServer', x=-312.44, y=4.00, z=-212.31], EntityItem['item.item.seeds'/78796, l='MpServer', x=-287.22, y=5.13, z=-149.91], EntityVillager['Villager'/6, l='MpServer', x=-300.56, y=4.00, z=-207.91], EntityVillager['Villager'/7, l='MpServer', x=-296.84, y=4.00, z=-208.34], EntityVillager['Villager'/8, l='MpServer', x=-307.03, y=4.00, z=-198.16], EntityVillager['Villager'/9, l='MpServer', x=-286.44, y=4.00, z=-199.88], EntityVillager['Villager'/10, l='MpServer', x=-305.16, y=5.50, z=-186.25], EntityVillager['Villager'/11, l='MpServer', x=-302.84, y=5.00, z=-196.50], EntityVillager['Villager'/12, l='MpServer', x=-310.22, y=4.00, z=-188.66], EntityVillager['Villager'/13, l='MpServer', x=-301.56, y=4.00, z=-209.16], EntityVillager['Villager'/14, l='MpServer', x=-299.47, y=4.00, z=-206.78], EntityVillager['Villager'/15, l='MpServer', x=-303.63, y=5.00, z=-211.63], EntityItem['item.item.seeds'/97938, l='MpServer', x=-267.16, y=4.13, z=-159.50], EntityVillager['Villager'/17, l='MpServer', x=-309.06, y=4.50, z=-203.88], EntityVillager['Villager'/16, l='MpServer', x=-286.66, y=4.00, z=-196.69], EntityVillager['Villager'/19, l='MpServer', x=-290.66, y=5.00, z=-198.69], EntityVillager['Villager'/18, l='MpServer', x=-293.25, y=4.00, z=-202.56], EntityVillager['Villager'/21, l='MpServer', x=-296.50, y=5.00, z=-190.72], EntityVillager['Villager'/20, l='MpServer', x=-285.31, y=4.00, z=-199.00], EntityVillager['Villager'/23, l='MpServer', x=-313.38, y=4.00, z=-202.50], EntityVillager['Villager'/22, l='MpServer', x=-309.28, y=4.00, z=-201.60], EntitySlime['Slime'/96377, l='MpServer', x=-385.57, y=4.00, z=-97.58], EntityVillager['Villager'/25, l='MpServer', x=-307.34, y=5.00, z=-214.34], EntitySlime['Slime'/116757, l='MpServer', x=-346.97, y=4.00, z=-159.72], EntityVillager['Villager'/24, l='MpServer', x=-315.53, y=5.00, z=-194.66], EntityVillager['Villager'/27, l='MpServer', x=-312.44, y=4.00, z=-209.25], EntityItem['item.item.seeds'/69947, l='MpServer', x=-294.47, y=5.13, z=-137.97], EntityItem['item.item.seeds'/79501, l='MpServer', x=-284.50, y=5.13, z=-150.66], EntityVillager['Villager'/26, l='MpServer', x=-312.16, y=4.00, z=-189.59], EntityVillager['Villager'/28, l='MpServer', x=-292.75, y=5.00, z=-209.44], EntityVillager['Villager'/30, l='MpServer', x=-290.22, y=4.00, z=-203.53], EntitySlime['Slime'/112177, l='MpServer', x=-377.69, y=4.00, z=-215.66], EntityItem['item.item.seeds'/120562, l='MpServer', x=-274.16, y=5.13, z=-155.28], EntityItem['item.item.seeds'/80094, l='MpServer', x=-283.53, y=5.13, z=-148.66], EntityItem['item.item.seeds'/115563, l='MpServer', x=-286.91, y=5.13, z=-148.38], EntityItem['item.item.seeds'/20019, l='MpServer', x=-330.13, y=5.13, z=-179.78], EntitySlime['Slime'/124542, l='MpServer', x=-375.88, y=4.00, z=-104.63], EntityChicken['Chicken'/48849, l='MpServer', x=-385.50, y=4.00, z=-90.50], EntityChicken['Chicken'/48848, l='MpServer', x=-381.50, y=4.00, z=-92.50], EntityItem['item.item.seeds'/78247, l='MpServer', x=-288.09, y=5.13, z=-151.38], EntityItem['item.item.seeds'/78246, l='MpServer', x=-287.38, y=5.13, z=-151.22], EntityItem['item.item.wheat'/78245, l='MpServer', x=-287.59, y=5.13, z=-151.50], EntitySlime['Slime'/99465, l='MpServer', x=-339.23, y=4.47, z=-166.85], EntityChicken['Chicken'/48847, l='MpServer', x=-377.50, y=4.00, z=-91.50], EntityItem['item.item.seeds'/123430, l='MpServer', x=-267.53, y=5.13, z=-158.09], EntitySlime['Slime'/111148, l='MpServer', x=-366.42, y=4.47, z=-156.76], EntitySlime['Slime'/121584, l='MpServer', x=-351.59, y=4.00, z=-172.69], EntityItem['item.item.wheat'/68898, l='MpServer', x=-297.44, y=5.13, z=-142.22], EntityIronGolem['Iron Golem'/67944, l='MpServer', x=-293.75, y=5.00, z=-203.88], EntityClientPlayerMP['JakeJake15'/31, l='MpServer', x=-324.64, y=5.62, z=-167.49]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:856)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Mac OS X (x86_64) version 10.9.1
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 115159032 bytes (109 MB) / 586153984 bytes (559 MB) up to 1065025536 bytes (1015 MB)
    JVM Flags: 1 total; -Xmx1G
    AABB Pool Size: 830 (46480 bytes; 0 MB) allocated, 16 (896 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 8 mods loaded, 8 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.45.953} [Forge Mod Loader](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.953} [Minecraft Forge](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.1.0e} [Thaumcraft](Thaumcraft4) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedThaumaturgy{0.0.20} [Advanced Thaumaturgy](AdvancedThaumaturgy-1.6.4-0.0.20.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkererKami{1.0} [Thaumic Tinkerer KAMI](ThaumicTinkererKAMI_j6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{2.3-102} [Thaumic Tinkerer](ThaumicTinkerer-2.3-102.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicExploration{0.5.1} [Thaumic Exploration](Thaumic Exploration 0.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6.4-Forge9.11.1.953
    LWJGL: 2.9.0
    OpenGL: Intel HD Graphics 3000 OpenGL Engine GL version 2.1 INTEL-8.18.28, Intel Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 211 (11816 bytes; 0 MB) allocated, 29 (1624 bytes; 0 MB) used

**Comment by Lycaonj** [comment]
As mentioned in the forum OP, AT build 20 is for 4.0.5b, not 4.1.
