### ISSUE TITLE
Research notes not appearing

### ISSUE THREAD

**Issue by Timelife** [Lycaonj/AdvancedThaumaturgy#21]
I just wanted to pop in and say that when the Mircolith or the node modifier icons are clicked in the Thauminomicon, a piece of paper is consumed and no note is added to my inventory. I do not know if this is a conflict with any of the other Thaumcraft addons I have, which are Forbidden Knowledge and Thaumic Exploration. Thank you for your time.

**Comment by Lycaonj** [comment]
Fixed in build 24 :)  http://ixios.net/dl/?AdvancedThaumaturgy-1.6.4-0.0.24.jar

**Comment by Timelife** [comment]
Sweet, thanks.
