### ISSUE TITLE
Server-side crash

### ISSUE THREAD

**Issue by SpitefulFox** [Lycaonj/AdvancedThaumaturgy#22]
Something in build 23 appears to be trying to access something that's client-only.  Causes servers to crash on startup.

Forge log here: http://pastebin.com/1YNzzGMp

Submitting this on behalf of someone without a github account.

**Comment by Mj11jM** [comment]
I can confirm this happens with build 24 as well

**Comment by Lycaonj** [comment]
Fixed, build 25  :)  http://ixios.net/dl/?AdvancedThaumaturgy-1.6.4-0.0.25.jar
