### ISSUE TITLE
Thaumonomicon/Arcane Crystal crash

### ISSUE THREAD

**Issue by efalder413** [Lycaonj/AdvancedThaumaturgy#23]
All Arcane Crystal upgrades crash the client in SSP when attempting to view the second page of the Thaumonomicon entry.

_Did not test in SMP._

**Comment by rye1994** [comment]
Can confirm this happening in SMP, I haven't got a crash log unforunetaly but the server doesn't doesn't actually crash.

**Comment by Lycaonj** [comment]
Fixed in build 26 :)
