### ISSUE TITLE
sentry crystal research

### ISSUE THREAD

**Issue by Rainboww** [Lycaonj/AdvancedThaumaturgy#25]
When clicking any of the sentry crystals in the thaumonomicon to research them, paper is consumed, but no research notes are given - and being unable to research them also makes it impossible to research TT's ichor and following, so we're kind of stuck here.
Using the latest build (25) with thaumcraft 4.1e

**Comment by TheLarorke** [comment]
This is also locking us out of KAMI research, even if we already fully researched prior to the update.

**Comment by Lycaonj** [comment]
Fixed on my end in build 26 :)  Added a couple of placeholder aspect costs.
