### ISSUE TITLE
at net.ixios.advancedthaumaturgy.AdvThaum.registerStuff(AdvThaum.java:234)

### ISSUE THREAD

**Issue by xKillerbees** [Lycaonj/AdvancedThaumaturgy#26]
http://pastebin.com/b6cft5Mj

Using .25

**Comment by izstas** [comment]
I guess you have disabled Essentia Engine in the config.

There's a missing check for null: https://github.com/Lycaonj/AdvancedThaumaturgy/blob/master/main/java/net/ixios/advancedthaumaturgy/AdvThaum.java#L233

**Comment by xKillerbees** [comment]
Correct

**Comment by Lycaonj** [comment]
Build 26 has the null check.  Let me know if this issue is still a problem.
