### ISSUE TITLE
Crash on startup if Buildcraft not installed

### ISSUE THREAD

**Issue by steelstiletto** [Lycaonj/AdvancedThaumaturgy#33]
I'm not actually positive if installing BC would resolve this issue, but the crash log is for a ClassNotFoundException and references the BC API.

Testing performed in a minimal environment with MultiMC.

Mods installed:
Forge 9.11.1.965
CodeChickenCore 0.9.0.9
NEI 1.6.1.9
Thaumcraft 4.1.0g
Advanced Thaumaturgy 0.0.25

Crashlog:
http://pastebin.com/BDe9ndxR

Forge log:
http://pastebin.com/u9wRiDPX

**Comment by Lycaonj** [comment]
I removed the accidental hard dependency on Buildcraft in build 26.
