### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by Rainboww** [Lycaonj/AdvancedThaumaturgy#35]
When trying to launch on a private modpack with the most recent 26 update, I got this crash: https://gist.github.com/Rainboww/a2906d5e34149bf9b286
Happens both for my friend with optifine and me without it, and doesn't happen on the server - that launches just fine.
In case it helps, the modack includes most Monster mods, with the latest thaumcraft, thaumic tinkerer, thaumic exploration, forbidden magic and electro-magic tools.
A fix/help would be appreciated!

**Comment by Lycaonj** [comment]
I could have swore I replied with a comment asking about your config, but it's not here... so... can you post up your config somewhere?  I suspect you have something disabled.  I believe I found and fixed this issue in build 28 but I'll need a look at your config first to be sure.

**Comment by Rainboww** [comment]
https://gist.github.com/Rainboww/d947e3443bef9b5a2452
It's our current config for build 25, but I didn't change it when downgrading back from 26 to 25, so it should still be the same file.
Also, about disabled items - I don't think I ever actually disabled any features of your mod myself, so I guess that whatever is disabled was disabled because it was still a WIP feature, but I don't really know what's completed and what isn't. 
Would you mind telling me what features are safe to  enable and are working? That'd be much appreciated!
EDIT: typo

**Comment by Lycaonj** [comment]
There are quite a few things disabled in your config;. however, I downloaded and used your config and fixed up any errors/crashes that were caused by disabled items, as well as giving a once-over to all the other items that can be disabled.
