### ISSUE TITLE
Ethereal Jars acting weird on crafting/placing

### ISSUE THREAD

**Issue by Keridos** [Lycaonj/AdvancedThaumaturgy#36]
Also: Ethereal jars are bugged, when you craft them you get one with a brown cap, then when you place them they turn into the white capped version. After harvesting those you get the white capped version that seems to have a max stacksize of 4.

**Comment by Lycaonj** [comment]
I can't seem to reproduce this bug; I get the silverwood-capped ethereal jars when crafting them.  They intentionally have a max stack size of 4.
