### ISSUE TITLE
Issues with the server help command

### ISSUE THREAD

**Issue by Malexion** [Lycaonj/AdvancedThaumaturgy#37]
It doesn't actually cause a crash but after a server has been loaded up in a console there seems to be a ClassCastException at (ATServerCommand. java: 46)

This occurs whenever I type "help" into the console, done with forge 965 on just a plain nogui server with AT 0.0.28

It says something about DedicatedServer cannot be cast to EntityPlayer.

**Comment by Lycaonj** [comment]
When I coded the command stuff, I did it assuming they'd always be sent in-game via a player.  I totally forgot you can send commands from the console.  I'll toss in a type check to prevent the issue.
