### ISSUE TITLE
Creative Nodes NOT containing all primal aspects (Although it says they do)

### ISSUE THREAD

**Issue by PyroplasmaKiwi** [Lycaonj/AdvancedThaumaturgy#41]
Creative Nodes only show every primal aspect if you look at them with goggles of revealing, but they don't actually contain all of the primal aspects, and I have been unable to find 1 with ordo in it. Can you try and fix it so they do have all the aspects so that wands can be recharged fully using them, because nodes with ordo in are awkward to find and they always deplete quickly.

**Comment by Lycaonj** [comment]
Fixed in 1.7.2 :)
