### ISSUE TITLE
Bad Node Modifier research

### ISSUE THREAD

**Issue by dark13th** [Lycaonj/AdvancedThaumaturgy#42]
The research for Node Modifier is unresearchable. AdvThaum 0.0.28.

![2014-05-05 17_03_13-greenshot](https://cloud.githubusercontent.com/assets/4464087/2877978/382efcd2-d456-11e3-9103-35db1ca071a6.png)

**Comment by miaowara** [comment]
This is not unresearchable, simply connect anything to the auram and it will complete.

**Comment by Lycaonj** [comment]
I'll tweak up the research a bit.  This is the kind of feedback I sorely need regarding AT, but until now, it's been completely absent.  Thanks for the report.
