### ISSUE TITLE
Advanced Thaumaturgy 1.7.2

### ISSUE THREAD

**Issue by XCreeper1207** [Lycaonj/AdvancedThaumaturgy#43]
When Will Advanced Thaumaturgy be for 1.7.2?

**Comment by Lycaonj** [comment]
I just changed AT from being a WIP mod to an actual released mod; there's a new post on the Minecraft Forums where you can get the new build for 1.7.2.  http://www.minecraftforum.net/topic/2697662-172-advanced-thaumaturgy-thaumcraft-addon/
