### ISSUE TITLE
AdvancedThaumaturgy Suggestion

### ISSUE THREAD

**Issue by XCreeper1207** [Lycaonj/AdvancedThaumaturgy#44]
I think that there needs to be an object to take out  aspects that isn't primal.
Example: A node has aqua and lux you can take out the lux aspect so there's another use for nodes then you could use the lux in the object and have sum kind of separator that takes out the lux from the object then have it turn into a liquid aspects that can be stored in a warded jar.  Also using the node modifier non primal nodes  but nodes have to spawn more often or there is another way to get Ethereal Essence.

**Comment by Lycaonj** [comment]
You can get Ethereal Essence from wisps.

Converting node vis to essentia isn't something I'm keen on.  Not going to outright say no, but it's not likely.  We had a discussion in #thaumcraft about it one evening and the general concensus was that it's something that'd not normally be possible according to the properties of aspects, vis, and essentia.
