### ISSUE TITLE
Essentia engine client update rate [version 0.0.28]

### ISSUE THREAD

**Issue by GammaPaladin** [Lycaonj/AdvancedThaumaturgy#45]
The Essentia Engine currently can't be used on my server, at least, not in any numbers, because it seems to be sending client updates to any player within rendering distance every single time it updates its "charge", which I'm guessing it does every tick.

This _quickly_ floods the upstream bandwidth of my server and everybody gets massive lag and disconnects.

I know the 1.6.4 version is old now, but could you possibly change the engine to throttle client updates, or only update the charge on the client side when the client requests the information?

**Comment by Lycaonj** [comment]
Yes, I can.  I still have the 1.6.4 source somewhere.  Just will have to wait until I manage to get a keyboard for my desktop (I'm on a tablet now).

**Comment by GammaPaladin** [comment]
Thanks for that. I like the engines, they make a really fun power source :)

**Comment by Lycaonj** [comment]
I've jumped to 1.7.10 this is fixed.  . -- Sorry this reply is months behind.  Health has been terrible and I am just now getting back into things.  If this is still an issue in 1.7.10 (after the build for it is posted) feel free to reopen.
