### ISSUE TITLE
Ethereal Jar Needs Work

### ISSUE THREAD

**Issue by Armigus** [Lycaonj/AdvancedThaumaturgy#46]
The ethereal jar has a few issues:
1. No aspects. It should at least honor the crafting recipe even if it's at the arcane worktable.
2. The essentia funnel from tinkerer does not respect its true capacity... it fills only to the normal jar's 64.
3. It cannot right-click on an alembic to collect its contents.

Is this fixable?

**Comment by Lycaonj** [comment]
I'll double check these issues in the 1.7.10 release.. -- Sorry this reply is months behind.  Health has been terrible and I am just now getting back into things.  If this is still an issue in 1.7.10 (after the build for it is posted) feel free to reopen.
