### ISSUE TITLE
Invisible research

### ISSUE THREAD

**Issue by Mrkwtkr** [Lycaonj/AdvancedThaumaturgy#48]
Researches of the Node Modifier,Thaumic Fertilizer and the Ethereal Jar are invisible in Thaumonomicon :( I have checked that they are 'true' in the config.....What happened?
![ss 2014-07-15 at 02 14 40](https://cloud.githubusercontent.com/assets/6889122/3581366/a36b37a6-0bea-11e4-871e-2e9c3e257d31.jpg)
![ss 2014-07-15 at 02 15 06](https://cloud.githubusercontent.com/assets/6889122/3581367/a370ca68-0bea-11e4-8909-dfb837cadf81.jpg)

**Comment by Lycaonj** [comment]
. -- Sorry this reply is months behind.  Health has been terrible and I am just now getting back into things.  If this is still an issue in 1.7.10 (after the build for it is posted) feel free to reopen.

**Comment by Mrkwtkr** [comment]
Update coming soon?

**Comment by Lycaonj** [comment]
1.7.10 test build is currently available on page 8ish on MCF:  http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091853-advanced-thaumaturgy-thaumcraft-addon?page=8

**Comment by Mrkwtkr** [comment]
Thank U :D
