### ISSUE TITLE
1.6.4 AT

### ISSUE THREAD

**Issue by meatball113** [Lycaonj/AdvancedThaumaturgy#50]
I have a ignis jar next to an essentia engine, the engine is connected to a wooden kinesis pipe, the wooden pipe connects to iron kinesis pipes which connect to my machines.

I have a gate in the wooden pipe that is set to power requested and redstone signal on. I've tried using a redstone lever/torch next to it but the engine will not activate at all, any ideas?

**Comment by Lycaonj** [comment]
Put essentia in the jar? -- Sorry this reply is 2 months behind.  Health has been terrible and I am just now getting back into things.  If this is still an issue in 1.7.10 (after the build for it is posted) feel free to reopen.
